---
title: "EDA plots"
output:
  pdf_document: default
  html_document: default
date: "2024-04-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
library(readxl)
library(tidyverse)
library(here)

path <- "data/train_dataset.xlsx"
path2 <- "data/reference values.xlsx"
sheets <- excel_sheets(path)

specTrain <- NULL
for(i in 1:length(sheets)){
  spec <- readxl::read_excel(path, sheet = sheets[i])
  spec <- spec |>
  mutate(`sample number` = rep(sheets[i], nrow(spec)))
  specTrain <- rbind(specTrain, spec)
}

labels <- readxl::read_excel(path2, sheet = excel_sheets(path2))
# specTrain |> glimpse()
specTrain <- specTrain |> left_join(labels)

# labels$`lactose content` |> table()
tbl <- sort(unique(labels$`lactose content`))
```


```{r}
for (i in 1:length(tbl)){
p1 <- specTrain |>
  mutate(ID = 1:nrow(specTrain)) |>
  # mutate(`sample number` = fct_reorder(as.factor(`sample number`), `lactose content`)) |>
  pivot_longer(-c(ID, `sample number`, `lactose content`)) |>
  mutate(name = as.numeric(name)) |>
  filter(`lactose content`==tbl[i]) |>
  ggplot(aes(x = name, y = value, group = ID, col = `sample number`)) +
  geom_line()+
  facet_wrap(~`sample number`)
print(p1)
}
```
