---
title: "EDA plots"
output:
  pdf_document: default
  html_document: default
date: "2024-04-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r}
library(readxl)
library(tidyverse)
library(here)

path <- "data/train_dataset.xlsx"
path2 <- "data/reference values.xlsx"
sheets <- excel_sheets(path)

specTrain <- NULL
for(i in 1:length(sheets)){
  spec <- readxl::read_excel(path, sheet = sheets[i])
  spec <- spec |>
  mutate(`sample number` = rep(sheets[i], nrow(spec)))
  specTrain <- rbind(specTrain, spec)
}

labels <- readxl::read_excel(path2, sheet = excel_sheets(path2))
# specTrain |> glimpse()
specTrain <- specTrain |> left_join(labels)

# labels$`lactose content` |> table()
tbl <- sort(unique(labels$`lactose content`))
```

```{r}
a <- specTrain |>
  group_by(`sample number`) |> 
  summarise(across(everything(), list(min = min, max = max))) |> 
  pivot_longer(-c(`sample number`))

a <- a |> 
  mutate(wave  = str_split(name, "_", simplify = TRUE)[,1], 
         name  = str_split(name, "_", simplify = TRUE)[,2])


a <-  a |>
  pivot_wider(names_from = name, values_from = value)
  
a <-  a |> mutate(wave = as.numeric(wave)) 

a <-  a |> left_join(labels)

```



```{r, fig.height=3, fig.width=12}
for (i in 1:length(tbl)){
p1 <-  a |> 
  filter(`lactose content`==tbl[i]) |>
  ggplot(aes(x = wave, col = `sample number`)) +
  geom_ribbon(aes(ymin=min, ymax=max, fill = `sample number`), alpha = 0.7) +
  facet_wrap(~`sample number`, nrow = 1)
print(p1)
}
```



