---
title: "EDA plots"
output:
  pdf_document: default
  html_document: default
date: "2024-04-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r}
library(readxl)
library(tidyverse)
library(here)
library(broom)
library(GGally)

path <- "data/train_dataset.xlsx"
path2 <- "data/reference values.xlsx"
sheets <- excel_sheets(path)

specTrain <- NULL
for(i in 1:length(sheets)){
  spec <- readxl::read_excel(path, sheet = sheets[i])
  spec <- spec |>
  mutate(`sample number` = rep(sheets[i], nrow(spec)))
  specTrain <- rbind(specTrain, spec)
}

labels <- readxl::read_excel(path2, sheet = excel_sheets(path2))
# specTrain |> glimpse()
specTrain <- specTrain |> left_join(labels)

# labels$`lactose content` |> table()
tbl <- sort(unique(labels$`lactose content`))
```

```{r}
# pc <- specTrain |> select(-c(`sample number`, `lactose content`)) |>
pc <- specTrain |> select(`412.71`: `3907.24`) |>
  prcomp(center = TRUE,
            scale. = TRUE)
```

```{r}
pc |>
  tidy(matrix = "eigenvalues") |>
  filter(PC < 8) |>
  ggplot(aes(PC, percent)) +
  geom_col(fill = "#56B4E9", alpha = 0.8)
```

```{r}
pc |> 
  augment(specTrain) |>
  ggplot(aes(.fittedPC1, .fittedPC2, color = as.factor(`lactose content`))) + 
  geom_point(size = 0.5, alpha = 0.5)

pc |> 
  augment(specTrain) |>
  ggplot(aes(.fittedPC1, .fittedPC3, color = as.factor(`lactose content`))) + 
  geom_point(size = 0.5, alpha = 0.5)


pc |> 
  augment(specTrain) |> 
  select(c(.fittedPC1: .fittedPC6, `lactose content`)) |>
  ggpairs(columns = 1:6, aes(colour = as.factor(`lactose content`)),
          lower = list(continuous = wrap("points", alpha = 0.5, size = 0.2)),
          upper = list(continuous = wrap("points", alpha = 0.5, size = 0.2)))




```


```{r}
pc |> 
  augment(specTrain) |>
  ggplot(aes(.fittedPC1, .fittedPC2, color = `sample number`)) + 
  geom_point(size = 0.5, alpha = 0.5)  + theme(legend.position = "none")

pc |> 
  augment(specTrain) |>
  ggplot(aes(.fittedPC2, .fittedPC3, color = `sample number`)) + 
  geom_point(size = 0.5, alpha = 0.5)  + theme(legend.position = "none")
  

pc |> 
  augment(specTrain) |> 
  select(c(.fittedPC1: .fittedPC6, `sample number`)) |>
  ggpairs(columns = 1:6, aes(colour = `sample number`),
          lower = list(continuous = wrap("points", alpha = 0.5, size = 0.2)),
          upper = list(continuous = wrap("points", alpha = 0.5, size = 0.2))) 



```
