---
title: "ML attempts"
output:
  pdf_document: default
  html_document: default
date: "2024-04-03"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```


```{r}

library(tidyverse)
library(ranger)

calcRMSE <- function(y, yhat){sqrt(mean((yhat - y)^2))}


specTrain <- readRDS("specTrain.rds")
specTest <- readRDS("specTest.rds")
# specTest |> glimpse()



sample <- specTrain$`sample number` |> unique()

sample_te <- specTest$`sample number` |> unique()

specTrain<- specTrain |> select(c(`412.71`: `3907.24`,`sample number`, `lactose content` )) 

specTest<- specTest |> select(c(`412.71`: `3907.24`,`sample number`))

set.seed(1951)


```



```{r}
dat.tr <- specTrain 
dat.te <- specTest

tr.samp <- dat.tr |> select(`sample number`)
dat.tr <- dat.tr |> select(-`sample number`)

te.samp <- dat.te |> select(`sample number`)
dat.te <- dat.te |> select(-`sample number`)


truth <- dat.tr |> 
  mutate(samp = tr.samp$`sample number`) |> 
  group_by(samp) |> 
  summarise(mn = mean(`lactose content`))



  y1 <- dat.tr$`lactose content`
  dat.tr$`lactose content` <- as.factor(dat.tr$`lactose content`)
  dat.tr <- dat.tr |> rename(Diet = `lactose content`)
```


```{r}

# ===================================
fit_lda <- MASS::lda(Diet ~ ., 
               dat.tr)
lda_tr <- as_tibble(as.matrix(dat.tr |> select(-Diet)) %*% fit_lda$scaling)


lda_te <- as_tibble(as.matrix(dat.te) %*% fit_lda$scaling)

    

rf.fit <- ranger(y = y1, x = lda_tr,  importance = "impurity")

  
  rf.pred.tr <- rf.fit |>   predict(data = lda_tr)

  rf.pred <- rf.fit |> predict(data = lda_te)

   pred_table <- tibble(pred =
                         as.numeric(rf.pred.tr$predictions)) |> 
    mutate(samp = tr.samp$`sample number`) |> 
    group_by(samp) |> 
    summarise(mn.pred = mean(pred), med.pred = median(pred)) |> 
    left_join(truth)
   
table(round(pred_table$med.pred), pred_table$mn)
   
calcRMSE( pred_table$mn,  pred_table$mn.pred)
calcRMSE( pred_table$mn,  pred_table$med.pred)
plot( pred_table$mn,  pred_table$mn.pred)
abline(a = 0, b = 1)
   
points( pred_table$mn,  pred_table$med.pred, col = 2)


pred_table_te <- tibble(pred =
                        as.numeric(rf.pred$predictions)) |> 
    mutate(samp = te.samp$`sample number`) |> 
    group_by(samp) |> 
    summarise(mn.pred = mean(pred), med.pred = median(pred), sd.pred = sd(pred)) 
 


pred_table_te |> ggplot(aes(med.pred, mn.pred)) + geom_point()
 
tibble(pred = as.numeric(rf.pred$predictions)) |> 
    mutate(samp = te.samp$`sample number`) |> ggplot(aes(samp, pred)) + geom_boxplot()
  
write.csv(pred_table_te, "KD_prediction3.csv")

 library(ggridges)

predPlot <- tibble(pred =
                         as.numeric(rf.pred$predictions)) |> 
    mutate(samp = te.samp$`sample number`)

 saveRDS(predPlot, "predPlot.rds")
predPlot |>   ggplot(aes(x= pred,y= samp, fill=samp))+
      geom_density_ridges(alpha = 0.5,jittered_points = TRUE, point_alpha=1,point_shape=21)
```
