---
title: "Surfaces and replicates"
output: pdf_document
date: "2024-07-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(broom)
library(GGally)
library(gridExtra)
library(RColorBrewer)
library(ggrepel)
substructure <- read.csv("surface.csv")
# substructure |> glimpse()
# substructure <- substructure |> rename(`sample number` = Sample)
substructure <- substructure |> rename(sample = Sample)

specTrain <- readRDS("specTrain.rds")
specTest <- readRDS("specTest.rds")
medoiddat <- readRDS("medoiddat.rds")
medoidtest <- readRDS("medoidtest.rds")
```


```{r}
medoiddat <- medoiddat  |> select(-`lactose content`)

medoiddat <- medoiddat |> left_join(substructure)
medoidtest <- medoidtest |> left_join(substructure)
medoids <- rbind(medoiddat, medoidtest)
# medoids |> glimpse()
medoids <- medoids |> mutate(label = gsub('sample', '', sample))
medoids <- medoids |> mutate(substruct = interaction(Ml, Surface))
lactose <- read.csv("data/CompleteReferences.csv")
medoids <- medoids |> left_join(lactose)

```

# MDS

```{r}

mds_meds <- medoids |> select(`412.71`: `3907.24`) |> dist() |> cmdscale()

mds_meds <- mds_meds |>   as_tibble() |> rename(MDS1 = V1, MDS2 = V2) |> cbind(medoids) |> mutate(label2 = label)
mds_meds$label2[mds_meds$train=="train"] <- NA
# Plot the results
mds_meds |> ggplot(aes(x = MDS1, y = MDS2, color = (Surface), label = label2)) +
  geom_point() +
  geom_text_repel(box.padding = 0.5) +
  ggtitle("Coloured by surface")+
theme(legend.position = "none")

p1 <- mds_meds |> ggplot(aes(x = MDS1, y = MDS2, color = as.factor(PredLDA), label = label2)) +
  geom_point() +
  geom_text_repel(box.padding = 0.5) +
  ggtitle("Coloured by LDA prediction")+
theme(legend.position = "none")


p2 <- mds_meds |> ggplot(aes(x = MDS1, y = MDS2, color = as.factor(lactose), label = label2)) +
  geom_point() +
  geom_text_repel(box.padding = 0.5) +
  ggtitle("Coloured by lactose")+
theme(legend.position = "none")

grid.arrange(p2, p1, nrow = 1)
# plot(mds_meds[, 1], mds_meds[, 2],
#      type = "n", xlab = "MDS Dimension 1",
#      ylab = "MDS Dimension 2")
# 
# points(mds_meds[, 1], mds_meds[, 2],
#        pch = 21, bg = as.factor(medoids$Surface))
# text(mds_meds[, 1], mds_meds[, 2],
#      labels = substr(medoids$label, 1, 2),
#      pos = 3, cex = 0.8)
# 
# 
# plot(mds_meds[, 1], mds_meds[, 2],
#      col = as.factor(medoids$lactose), pch = 8)


# points(mds_meds[, 1], mds_meds[, 2],
#        pch = 21, bg = as.factor(medoids$lactose))
# text(mds_meds[, 1], mds_meds[, 2],
#      labels = substr(medoids$label, 1, 2),
#      pos = 3, cex = 0.8)

```

```{r}

pc <- medoids |> select(`412.71`: `3907.24`) |>
  prcomp(center = TRUE,
         scale. = TRUE)

medoids <- medoids |>  mutate(label2 = label)
medoids$label2[medoids$train=="train"] <- NA

p1 <- pc |>
  augment(medoids) |>
  ggplot(aes(.fittedPC1, .fittedPC2, color = (Surface), label = label2)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  ylab("PC2") +
  xlab("PC1") +
theme(legend.position = "none")

p2 <- pc |>
  augment(medoids) |>
  ggplot(aes(.fittedPC1, .fittedPC3, color =(Surface), label = label2)) +
  geom_point() +
  geom_text_repel(box.padding = 0.5)+
  ylab("PC3") +
  xlab("PC1") +
theme(legend.position = "none")

grid.arrange(p1, p2, nrow = 1)


```


```{r}


p1 <- pc |>
  augment(medoids) |>
  ggplot(aes(.fittedPC1, .fittedPC2, color = lactose, label = label2)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  ylab("PC2") +
  xlab("PC1") +
theme(legend.position = "none")+ scale_color_gradient(low = "blue", high = "red")+
  ggtitle("Coloured by lactose")

# + scale_color_gradient2(midpoint = mean(medoids$lactose), low = "blue", mid = "white",
                            # high = "red", space = "Lab" )

p2 <- pc |>
  augment(medoids) |>
  ggplot(aes(.fittedPC1, .fittedPC3, color = lactose, label = label2)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  ylab("PC3") +
  xlab("PC1") +
theme(legend.position = "none") + 
  scale_color_gradient(low = "blue", high = "red")+
  ggtitle("Coloured by lactose")

# + scale_color_gradient2(midpoint = mean(medoids$lactose), low = "blue", mid = "white",
                            # high = "red", space = "Lab" )



p3 <- pc |>
  augment(medoids) |>
  ggplot(aes(.fittedPC1, .fittedPC2, color = PredRF, label = label2)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  ylab("PC2") +
  xlab("PC1") +
theme(legend.position = "none")+ scale_color_gradient(low = "blue", high = "red")+
  ggtitle("Coloured by RF prediction")

# + scale_color_gradient2(midpoint = mean(medoids$lactose), low = "blue", mid = "white",
                            # high = "red", space = "Lab" )

p4 <- pc |>
  augment(medoids) |>
  ggplot(aes(.fittedPC1, .fittedPC3, color = PredRF, label = label2)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  ylab("PC3") +
  xlab("PC1") +
theme(legend.position = "none") + 
  scale_color_gradient(low = "blue", high = "red")+
  ggtitle("Coloured by RF prediction")

grid.arrange(p1, p2, p3, p4, nrow = 2)


```

```{r}
dat.tr <- specTrain
dat.tr <- dat.tr |> select(-c(`sample number`))
# dat.tr <- dat.tr |> select(-c(`sample number`, Ml, Surface, Replicate))
dat.tr$`lactose content` <- as.factor(dat.tr$`lactose content`)
dat.tr <- dat.tr |> rename(Diet = `lactose content`)
fit_lda <- MASS::lda(Diet ~ .,
                     dat.tr|> select(`412.71`: `3907.24`, Diet))
```


```{r}
lda_meds  <-  as_tibble(as.matrix(medoids |> select(`412.71`: `3907.24`)) %*% fit_lda$scaling)
lda_meds <- lda_meds |> mutate(Surface=medoids$Surface,
                               label = medoids$label2,
                               Ml = medoids$Ml,
                               substruct = medoids$substruct,
                               lactose = medoids$lactose,
                               PredLDA = medoids$PredLDA,
                               PredRF = medoids$PredRF)
# table(lda_meds$Ml, lda_meds$lactose)
```


```{r}
p4 <- lda_meds %>%
  ggplot(aes(x = LD1, y = LD2, col = as.factor(lactose), label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")

p5 <- lda_meds %>%
  ggplot(aes(x = LD3, y = LD4, col = as.factor(lactose), label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")

p6 <- lda_meds %>%
  ggplot(aes(x = LD5, y = LD6, col = as.factor(lactose), label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")

p7 <- lda_meds %>%
  ggplot(aes(x = LD2, y = LD7, col = as.factor(lactose), label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")
grid.arrange(p4, p5, p6, p7, nrow = 2)
```

```{r}
p4 <- lda_meds %>%
  ggplot(aes(x = LD1, y = LD2, col = lactose, label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+ 
  scale_color_gradient(low = "blue", high = "red")

p5 <- lda_meds %>%
  ggplot(aes(x = LD3, y = LD4, col = lactose, label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+ 
  scale_color_gradient(low = "blue", high = "red")

p6 <- lda_meds %>%
  ggplot(aes(x = LD5, y = LD6, col = lactose, label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+ 
  scale_color_gradient(low = "blue", high = "red")

p7 <- lda_meds %>%
  ggplot(aes(x = LD2, y = LD7, col = lactose, label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+ 
  scale_color_gradient(low = "blue", high = "red")
grid.arrange(p4, p5, p6, p7, nrow = 2)
```




```{r}
p4 <- lda_meds %>%
  ggplot(aes(x = LD1, y = LD2, col = as.factor(lactose), label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+
  ggtitle("Coloured by lactose")

p5 <- lda_meds %>%
  ggplot(aes(x = LD3, y = LD4, col = as.factor(lactose), label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+
  ggtitle("Coloured by lactose")

p6 <- lda_meds %>%
  ggplot(aes(x = LD5, y = LD6, col = as.factor(lactose), label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+
  ggtitle("Coloured by lactose")

p7 <- lda_meds %>%
  ggplot(aes(x = LD1, y = LD2, col = as.factor(PredLDA), label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+
  ggtitle("Coloured by LDA prediction")

p8 <- lda_meds %>%
  ggplot(aes(x = LD3, y = LD4, col = as.factor(PredLDA), label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+
  ggtitle("Coloured by LDA prediction")

p9 <- lda_meds %>%
  ggplot(aes(x = LD5, y = LD6, col = as.factor(PredLDA), label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+
  ggtitle("Coloured by LDA prediction")

grid.arrange(p4, p7,p5, p8,p6, p9, nrow = 3)
```

```{r}
p4 <- lda_meds %>%
  ggplot(aes(x = LD1, y = LD2, col = lactose, label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+ 
  scale_color_gradient(low = "blue", high = "red")+
  ggtitle("Coloured by lactose")

p5 <- lda_meds %>%
  ggplot(aes(x = LD3, y = LD4, col = lactose, label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+ 
  scale_color_gradient(low = "blue", high = "red")+
  ggtitle("Coloured by lactose")

p6 <- lda_meds %>%
  ggplot(aes(x = LD5, y = LD6, col = lactose, label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+ 
  scale_color_gradient(low = "blue", high = "red")+
  ggtitle("Coloured by lactose")

p7 <- lda_meds %>%
  ggplot(aes(x = LD1, y = LD2, col = PredRF, label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+ 
  scale_color_gradient(low = "blue", high = "red")+
  ggtitle("Coloured by RF prediction")

p8 <- lda_meds %>%
  ggplot(aes(x = LD3, y = LD4, col = PredRF, label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+ 
  scale_color_gradient(low = "blue", high = "red")+
  ggtitle("Coloured by RF prediction")

p9 <- lda_meds %>%
  ggplot(aes(x = LD5, y = LD6, col = PredRF, label = label)) +
geom_point() +
  geom_text_repel(box.padding = 0.5)+
  theme(legend.position = "none")+ 
  scale_color_gradient(low = "blue", high = "red")+
  ggtitle("Coloured by RF prediction")


grid.arrange(p4, p7,p5, p8,p6, p9, nrow = 3)
```


